language: php

php:
  - '7.2'
  - '7.3'
  
cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-lowest --prefer-source --no-interaction

notifications:
    on_success: never
    on_failure: always